// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://garjhmlppiytgsarrouq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhcmpobWxwcGl5dGdzYXJyb3VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzU2MTUsImV4cCI6MjA2ODkxMTYxNX0.8WKaHfwGFnqN0hVfqbni0Y9BT0LGIv0S3PsHrWhSBQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});